version: '1'
services:
  nginx-react:
    image: reactapp:latest
    container_name: myreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports: [80:80]
    entrypoint: 
      NODE_ENV: "production"