version: '3'
services:
  react-app:
    #build will be overwriting in dev or prod case, so we can keep it here
    build: 
      context: .
      dockerfile: Dockerfile.dev

    #env_file:
    #  - ./.env
  