version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - REACT_APP_NAME=khaled-prod
      - CHOKIDAR_USEPOLLING=true
    #env_file:
    #  - ./.env
  